### PR TITLE
No default value in textarea

### PR DESCRIPTION
**Pull request by lucarabistouille**
At least, as the default value is not practical.
issue #11 
previous pull request #12

### CODE REVIEW

**Comment by LGD-Fr** [comment]
Please add elsewhere a link to a Markdown documentation.

**Comment by LGD-Fr** [comment]
The default value is self explaining, at least.

**Comment by LGD-Fr** [comment]
Please use the `{% trans %}` template tag and translate this in French and German ;-) @luc--

**Comment by lucarabistouille** [comment]
J’y songe.

**Pull request merged**
